version: '3.4'

services:
  app:
    build:
      context: ./blog-backend
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - ./blog-backend:/app
    env_file: ./blog-backend/.env
    environment:
      RAILS_ENV: development
  front:
    build:
      context: ./blog-frontend
      dockerfile: Dockerfile
    depends_on: 
      - app
    ports: 
      - "3001:3001"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  database:
    image: postgres:12.1
    ports:
    - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql